'use client';

import {ResponseText} from '@/components/response-text';
import { SkeletonRows } from '@/components/ui/activity';
import { useEffect, useRef, useState } from 'react';
import { FileText, FolderOpen, Plus, FilePenLine, Wallet, ArrowRight, Download } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { currencies, money, type Line } from '@/lib/workspace-rules';

type Business = { id: string; name: string; currency: string; stage: string; context: string };
type Document = { id: string; title: string; kind: string; content: string; evidence_status: string; filename: string | null; project_id: string | null; source_ids: string[]; created_at: string };
type Financial = { id: string; kind: string; number: string; status: string; currency: string; total_minor: number; paid_minor: number; issued_at: string | null; payment_reference?: string; details: { lines: Line[]; seller: string; buyer: string; terms: string; dueDate: string; notes: string; paymentDate?: string; invoiceNumber?: string } };
type Data = { business: Business; documents: Document[]; financials: Financial[]; projects: { id: string; name: string }[] };
type Draft = { content: string; sources: { id: string; title: string; number: number }[] };
const day = () => new Date().toISOString().slice(0, 10);

async function request(body: Record<string, unknown>) {
  const response = await fetch('/api/admin/workspaces', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const data = await response.json() as Record<string, unknown>;
  if (!response.ok) throw new Error(String(data.error || 'The action did not save.'));
  return data;
}

export function BusinessWorkspace() {
  const [businesses, setBusinesses] = useState<Business[]>([]), [businessId, setBusinessId] = useState('');
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(''), [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [tab, setTab] = useState('documents');
  const [create, setCreate] = useState(false), [selected, setSelected] = useState<string[]>([]), [projectId, setProjectId] = useState('');
  const [search, setSearch] = useState(''), [draft, setDraft] = useState<Draft | null>(null), [task, setTask] = useState('brief');
  const [question, setQuestion] = useState(''), [draftTitle, setDraftTitle] = useState(''), [financial, setFinancial] = useState<Financial | null>(null);
  const [printDocument, setPrintDocument] = useState<Document | null>(null);
  const fileReadId = useRef(0);
  const [file, setFile] = useState<File | null>(null), [content, setContent] = useState('');
  const [editingFinancial, setEditingFinancial] = useState<Financial | null>(null);
  const [lines, setLines] = useState([{ description: '', quantity: '1', unitPrice: '' }]);

  async function loadBusinesses() {
    const response = await fetch('/api/admin/workspaces'); const result = await response.json() as { businesses: Business[]; error?: string };
    if (!response.ok) throw new Error(result.error);
    setBusinesses(result.businesses); return result.businesses;
  }
  async function reload() {
    const response = await fetch(`/api/admin/workspaces?businessId=${encodeURIComponent(businessId)}`); const result = await response.json() as Data & { error?: string };
    if (!response.ok) throw new Error(result.error); setData(result);
    if (financial) setFinancial(result.financials.find(f => f.id === financial.id) || null);
  }
  useEffect(() => { loadBusinesses().then(list => { if (list.length) setBusinessId(list[0].id); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => {
    fileReadId.current++; setData(null); setSelected([]); setDraft(null); setFinancial(null); setPrintDocument(null); setProjectId(''); setError(''); setMessage(''); setFile(null); setContent(''); setEditingFinancial(null); setLines([{ description: '', quantity: '1', unitPrice: '' }]);
    if (!businessId) return; const controller = new AbortController(); setLoading(true);
    fetch(`/api/admin/workspaces?businessId=${encodeURIComponent(businessId)}`, { signal: controller.signal }).then(async r => { const d = await r.json() as Data & { error?: string }; if (!r.ok) throw new Error(d.error); setData(d); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [businessId]);
  async function run(work: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  const visible = data?.documents.filter(d => (!projectId || d.project_id === projectId) && `${d.title} ${d.content}`.toLowerCase().includes(search.toLowerCase())) || [];
  const projectSelect = <label>Project (optional)<select value={projectId} onChange={e => setProjectId(e.target.value)} disabled={busy}><option value="">Business-wide</option>{data?.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;
  function print() { window.print(); }

  return <>
    <div className="ws-no-print">
      <header className="admin-header"><div><small>BUSINESS WORKSPACE</small><h1>Clients &amp; billing</h1><p>Source documents, reviewed proposals and financial records, connected to one business.</p></div><a className="ws-demo-link" href="/workspace-demo">Try the example workspace <ArrowRight size={16} /></a></header>
      <div className="ws-toolbar"><label>Business<select value={businessId} onChange={e => setBusinessId(e.target.value)} disabled={busy || loading}><option value="">Choose a business</option>{businesses.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button onClick={() => setCreate(!create)} disabled={busy}><Plus size={17} /> New business</button><button onClick={() => run(async () => { await loadBusinesses(); if (businessId) await reload(); })} disabled={busy}>Refresh</button></div>
      {error && <p className="ws-alert" role="alert">{error}</p>}{message && <p className="ws-success" role="status">{message}</p>}
      {create && <form className="ws-card ws-form" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const fields = new FormData(form); void run(async () => { const result = await request({ action: 'createBusiness', name: fields.get('name'), currency: fields.get('currency'), context: fields.get('context') }); await loadBusinesses(); setBusinessId(String(result.id)); setCreate(false); }); }}><h2>Open a business file</h2><label>Business or working name<input name="name" required maxLength={160} /></label><label>Default currency<select name="currency" defaultValue="GHS">{currencies.map(c => <option key={c}>{c}</option>)}</select></label><label>Context and open questions<textarea name="context" rows={3} placeholder="Relationship, current stage and what still needs confirming" maxLength={4000} /></label><p className="ws-note">Starts as a prospect. A business file does not imply a signed client or confirmed legal identity.</p><button disabled={busy}>Create workspace</button></form>}
      {loading && <SkeletonRows rows={4} label="Loading your records" />}
      {!loading && !businessId && !create && <div className="ws-empty"><FolderOpen size={32} /><h2>Start with a business, even before a project exists.</h2><p>Keep research and discovery here. Add proposals and billing when the scope is ready.</p><button onClick={() => setCreate(true)}>Open the first business file</button></div>}
      {data && <>
        <div className="ws-context"><div><span className="ws-badge">{data.business.stage}</span><h2>{data.business.name}</h2><details><summary>Context and open questions</summary><p>{data.business.context || 'Add background as a source note. Keep assumptions visible until confirmed.'}</p></details></div><div className="ws-counts"><span><strong>{data.documents.length}</strong> documents</span><span><strong>{data.financials.filter(f => f.kind === 'invoice').length}</strong> invoices</span><span><strong>{data.business.currency}</strong> default currency</span></div></div>
        <Tabs value={tab} onValueChange={value => setTab(String(value))}>
          <TabsList className="ws-tabs"><TabsTrigger value="documents"><FolderOpen size={17} /> Documents</TabsTrigger><TabsTrigger value="assistant"><FilePenLine size={17} /> Assistant</TabsTrigger><TabsTrigger value="finance"><Wallet size={17} /> Financials</TabsTrigger></TabsList>
          <TabsContent value="documents">
            <div className="ws-grid"><section className="ws-card"><div className="ws-section-head"><h2>Source library</h2><span>{selected.length}/6 for AI</span></div><label>Search documents<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Title or document text" /></label>{projectSelect}
              <div className="ws-doc-list">{!visible.length && <p className="ws-note">No matching documents. Add a note or upload your first file.</p>}{visible.map(doc => <article key={doc.id}><div className="ws-doc-top"><label className="ws-check"><input type="checkbox" checked={selected.includes(doc.id)} disabled={busy || (!selected.includes(doc.id) && selected.length >= 6)} onChange={e => setSelected(current => e.target.checked ? [...current, doc.id] : current.filter(id => id !== doc.id))} /><span>{doc.title}</span></label><span className="ws-badge">{doc.evidence_status.replaceAll('_', ' ')}</span></div><p className="ws-note">{doc.kind} · {new Date(doc.created_at).toLocaleDateString()} {doc.filename && `· ${doc.filename}`}</p><details><summary>Read document</summary><div className="ws-document-text">{doc.content || 'Original file stored. Add a separate text note to make its contents available to AI.'}</div>{doc.source_ids?.length > 0 && <p className="ws-note">Sources: {doc.source_ids.map(id => data.documents.find(d => d.id === id)?.title || id).join(', ')}</p>}</details><div className="ws-row">{doc.filename && <a href={`/api/admin/workspaces?businessId=${businessId}&download=${doc.id}`}><Download size={15} /> Original file</a>}<button onClick={() => { setFinancial(null); setPrintDocument(doc); }}>Prepare print / PDF</button></div></article>)}</div>
              <button className="ws-primary" onClick={() => setTab('assistant')} disabled={!selected.length}><FilePenLine size={17} /> Work with selected documents</button>
            </section>
            <form className="ws-card ws-form" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const fields = new FormData(form); void run(async () => { let fileBase64: string | null = null; if (file) { if (file.size > 2_000_000) throw new Error('Choose a file up to 2 MB.'); const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''; for (const b of bytes) binary += String.fromCharCode(b); fileBase64 = btoa(binary); } await request({ action: 'saveDocument', businessId, projectId, title: fields.get('title'), kind: fields.get('kind'), evidenceStatus: fields.get('evidence'), content, filename: file?.name, fileBase64 }); form.reset(); setContent(''); setFile(null); await reload(); setMessage('Document saved to this business.'); }); }}>
              <h2>Add to the business file</h2><label>Title<input name="title" required maxLength={200} /></label><div className="ws-two"><label>Document type<select name="kind"><option value="note">Note</option><option value="research">Research</option><option value="discovery">Discovery</option><option value="proposal">Proposal</option><option value="scope">Scope of work</option><option value="handover">Handover</option><option value="file">Other file</option></select></label><label>Source status<select name="evidence"><option value="unverified">Unverified / research</option><option value="client_confirmed">Client confirmed</option><option value="internal">Internal working document</option><option value="ai_draft">AI draft</option></select></label></div>{projectSelect}<label>Original file (optional)<input type="file" accept=".txt,.md,.pdf,.docx,.png,.jpg,.jpeg" onChange={e => { const next = e.target.files?.[0] || null; const readId = ++fileReadId.current; setFile(next); setContent(''); if (next && /\.(txt|md)$/i.test(next.name)) { if (next.size > 80000) { setError('Text files for AI must be at most 80 KB.'); return; } void next.text().then(text => { if (readId === fileReadId.current) setContent(text); }); } }} /></label><p className="ws-note">Up to 2 MB per file. TXT and Markdown fill the text below. For PDF, Word or images, add readable notes for AI; the original stays available to download.</p><label>Document text or source notes<textarea rows={10} value={content} onChange={e => setContent(e.target.value)} maxLength={80000} placeholder="Paste the source text. Label what is confirmed, assumed or still unknown." /></label><button className="ws-primary" disabled={busy}>{busy ? 'Saving…' : 'Save document'}</button>
            </form></div>
          </TabsContent>
          <TabsContent value="assistant"><div className="ws-grid"><section className="ws-card ws-form"><h2>Prepare the next useful document</h2><p>The assistant reads only the selected source text and this business context. It cannot send documents, issue invoices or record payments.</p><div className="ws-source-list">{selected.map(id => <span key={id}><FileText size={15} />{data.documents.find(d => d.id === id)?.title}</span>)}{!selected.length && <p>No sources selected. Choose documents from the library first.</p>}</div><button onClick={() => setTab('documents')}>Choose source documents</button><label>Task<select value={task} onChange={e => setTask(e.target.value)}><option value="brief">Prepare discovery brief</option><option value="proposal">Draft proposal</option><option value="scope">Draft scope of work</option><option value="handover">Prepare handover checklist</option><option value="finance">Check billing readiness</option><option value="answer">Ask about these documents</option></select></label>{task === 'answer' && <label>Your question<textarea value={question} onChange={e => setQuestion(e.target.value)} maxLength={1000} /></label>}<p className="ws-note">Selected text will be sent to Aksen’s configured AI provider. Include only material suitable for that processing.</p><button className="ws-primary" disabled={busy || !selected.length} onClick={() => run(async () => { setDraft(null); const result = await request({ action: 'assist', businessId, sourceIds: selected, task, question }); setDraft(result as unknown as Draft); setDraftTitle(`${data.business.name} · ${task === 'answer' ? 'Source answer' : task}`); })}>{busy ? 'Preparing…' : 'Prepare a draft'}</button></section>
            <section className="ws-card ws-form"><div className="ws-section-head"><h2>Review before using</h2><span className="ws-badge">AI draft</span></div>{draft ? <><label>Document title<input value={draftTitle} onChange={e => setDraftTitle(e.target.value)} maxLength={200} /></label><details className="response-preview"><summary>Reading preview</summary><ResponseText text={draft.content}/></details><label>Review and edit<textarea rows={20} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} /></label><ol>{draft.sources.map(source => <li key={source.id}>[{source.number}] {source.title}</li>)}</ol>{projectSelect}<button disabled={busy || !draftTitle.trim()} onClick={() => run(async () => { await request({ action: 'saveDocument', businessId, projectId, title: draftTitle, kind: ['proposal','scope','handover'].includes(task) ? task : 'note', evidenceStatus: 'ai_draft', content: draft.content, sourceIds: draft.sources.map(s => s.id) }); await reload(); setDraft(null); setMessage('Draft saved with its source references. It has not been sent or approved.'); })}>Save reviewed draft to library</button></> : <div className="ws-empty"><FilePenLine size={30} /><p>Your draft will appear here with source references. Check every commitment and open question before sharing it.</p></div>}</section></div></TabsContent>
          <TabsContent value="finance">
            <div className="ws-balances">{[...new Set(data.financials.filter(f => f.kind === 'invoice' && ['issued','paid'].includes(f.status)).map(f => f.currency))].map(currency => { const invoices = data.financials.filter(f => f.kind === 'invoice' && ['issued','paid'].includes(f.status) && f.currency === currency); return <div className="ws-card" key={currency}><small>{currency} INVOICES</small><strong>{money(invoices.reduce((sum, f) => sum + f.total_minor - f.paid_minor, 0), currency)}</strong><span>Outstanding · {money(invoices.reduce((sum, f) => sum + f.paid_minor, 0), currency)} recorded received</span></div>; })}</div>
            <div className="ws-grid"><section className="ws-card"><h2>Financial register</h2><p className="ws-note">Draft → issue → record payment → receipt. Proformas are estimates and do not count as receivables. Currency totals stay separate.</p>{!data.financials.length && <p>No financial documents yet. Confirm scope and commercial terms before issuing one.</p>}<div className="ws-fin-list">{data.financials.map(f => <button key={f.id} onClick={() => { setPrintDocument(null); setFinancial(f); }}><span><strong>{f.number}</strong><small>{f.kind} · {f.status}</small></span><b>{money(f.total_minor, f.currency)}</b></button>)}</div>
              {financial && <div className="ws-fin-detail"><h3>{financial.number}</h3><p>{financial.kind} · {financial.status}</p><div className="ws-row"><button onClick={() => { setPrintDocument(null); setMessage('Print preview is below the workspace. Use Print / save PDF after reviewing it.'); }}>Prepare print / PDF</button>{financial.status === 'draft' && <button disabled={busy} onClick={() => { setEditingFinancial(financial); setLines(financial.details.lines.map(l => ({ description: l.description, quantity: String(l.quantity), unitPrice: (l.unitMinor / 100).toFixed(2) }))); }}>Edit draft</button>}{financial.status === 'draft' && <button disabled={busy} className="ws-primary" onClick={() => run(async () => { await request({ action: 'issue', businessId, financialId: financial.id }); await reload(); setMessage('Document issued and locked. Nothing has been emailed.'); })}>Confirm details and issue</button>}{['draft','issued'].includes(financial.status) && financial.kind !== 'receipt' && financial.paid_minor === 0 && <button disabled={busy} onClick={() => run(async () => { await request({ action: 'void', businessId, financialId: financial.id }); await reload(); setMessage('Document voided. Its record is retained.'); })}>Void document</button>}</div>
                {financial.kind === 'invoice' && financial.status === 'issued' && <form className="ws-form" onSubmit={e => { e.preventDefault(); const fields = new FormData(e.currentTarget); void run(async () => { await request({ action: 'payment', businessId, financialId: financial.id, amount: fields.get('amount'), reference: fields.get('reference'), paymentDate: fields.get('paymentDate') }); await reload(); setMessage('Payment recorded. A linked receipt is now in the register.'); }); }}><h3>Record money received</h3><p>Outstanding: {money(financial.total_minor - financial.paid_minor, financial.currency)}. Check your bank or payment record first.</p><label>Amount received ({financial.currency})<input name="amount" inputMode="decimal" required placeholder="0.00" /></label><label>Bank / payment reference<input name="reference" required maxLength={160} /></label><label>Received on<input name="paymentDate" type="date" required defaultValue={day()} max={day()} /></label><button disabled={busy}>Confirm payment and create receipt</button></form>}
              </div>}
            </section>
            <form key={editingFinancial?.id || 'new-financial'} className="ws-card ws-form" onSubmit={e => { e.preventDefault(); const fields = new FormData(e.currentTarget); void run(async () => { await request({ action: editingFinancial ? 'updateFinancial' : 'createFinancial', financialId: editingFinancial?.id, businessId, projectId, kind: editingFinancial?.kind || fields.get('kind'), currency: fields.get('currency'), seller: fields.get('seller'), buyer: fields.get('buyer'), terms: fields.get('terms'), dueDate: fields.get('dueDate'), notes: fields.get('notes'), lines }); await reload(); setMessage('Financial draft saved. Select it in the register to review and issue.'); }); }}><h2>{editingFinancial ? `Edit ${editingFinancial.number}` : 'Prepare a financial document'}</h2>{editingFinancial && <button type="button" onClick={() => { setEditingFinancial(null); setLines([{ description: '', quantity: '1', unitPrice: '' }]); }}>Create a new document instead</button>}<div className="ws-two"><label>Type<select name="kind" defaultValue={editingFinancial?.kind || 'proforma'} disabled={!!editingFinancial}><option value="proforma">Proforma</option><option value="invoice">Invoice</option></select></label><label>Currency<select name="currency" defaultValue={editingFinancial?.currency || data.business.currency}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label></div>{projectSelect}<label>Issuer / billing identity<textarea name="seller" defaultValue={editingFinancial?.details.seller} required rows={3} placeholder="Your confirmed legal/trading name, address, contact and any required registration details" /></label><label>Bill to<textarea name="buyer" required rows={3} defaultValue={editingFinancial?.details.buyer || data.business.name} /></label>
              <div className="ws-line-items">{lines.map((line, index) => <fieldset key={index}><legend>Item {index + 1}</legend><label>Description<input required value={line.description} onChange={e => setLines(lines.map((l, i) => i === index ? { ...l, description: e.target.value } : l))} /></label><div className="ws-two"><label>Quantity<input required type="number" min="1" max="10000" step="1" value={line.quantity} onChange={e => setLines(lines.map((l, i) => i === index ? { ...l, quantity: e.target.value } : l))} /></label><label>Unit price<input required inputMode="decimal" value={line.unitPrice} onChange={e => setLines(lines.map((l, i) => i === index ? { ...l, unitPrice: e.target.value } : l))} /></label></div>{lines.length > 1 && <button type="button" onClick={() => setLines(lines.filter((_, i) => i !== index))}>Remove item</button>}</fieldset>)}</div><button type="button" disabled={lines.length >= 30} onClick={() => setLines([...lines, { description: '', quantity: '1', unitPrice: '' }])}><Plus size={16} /> Add line item</button><label>Due date (optional)<input type="date" name="dueDate" defaultValue={editingFinancial?.details.dueDate} /></label><label>Payment terms and instructions<textarea name="terms" defaultValue={editingFinancial?.details.terms} required rows={3} placeholder="Agreed payment schedule and verified payment instructions" /></label><label>Notes / tax treatment<textarea name="notes" defaultValue={editingFinancial?.details.notes} rows={3} placeholder="Confirm applicable tax treatment before issue. No tax rate is applied automatically." /></label><button className="ws-primary" disabled={busy}>{editingFinancial ? 'Save draft changes' : 'Save financial draft'}</button><p className="ws-note">Amounts are calculated on the server. Issued records cannot be edited. This register tracks billing and manually recorded payments; it does not reconcile your bank or file taxes.</p></form>
            </div>
          </TabsContent>
        </Tabs>
      </>}
    </div>
    {(financial || printDocument) && <section className="ws-print-sheet"><div className="ws-no-print ws-row"><h2>Document preview</h2><button onClick={print}>Print / save PDF</button><button onClick={() => { setFinancial(null); setPrintDocument(null); }}>Close preview</button></div>{financial ? <><header><strong>{financial.details.seller}</strong><div><h1>{financial.kind.toUpperCase()}</h1><p>{financial.number}</p><b>{financial.status.toUpperCase()}</b></div></header><p>Issued: {financial.issued_at ? new Date(financial.issued_at).toLocaleDateString() : 'Not issued'}</p><h3>{financial.kind === 'receipt' ? 'Received from' : 'Bill to'}</h3><p className="ws-pre">{financial.details.buyer}</p>{financial.kind === 'receipt' ? <><p>Invoice: {financial.details.invoiceNumber}</p><p>Received on: {financial.details.paymentDate}</p><p>Reference: {financial.payment_reference}</p><h2>Received {money(financial.total_minor, financial.currency)}</h2><p>Payment recorded by Aksen. This document is not independent bank verification.</p></> : <><div className="ws-table-wrap"><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{financial.details.lines.map((line, i) => <tr key={i}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.unitMinor, financial.currency)}</td><td>{money(line.unitMinor * line.quantity, financial.currency)}</td></tr>)}</tbody></table></div><h2>Total {money(financial.total_minor, financial.currency)}</h2>{financial.details.dueDate && <p>Due: {financial.details.dueDate}</p>}<h3>Payment terms</h3><p className="ws-pre">{financial.details.terms}</p><p className="ws-pre">{financial.details.notes}</p>{financial.kind === 'proforma' && <p>Proforma only. This is not an issued invoice or proof of payment.</p>}</>}</> : printDocument && <><small>{printDocument.evidence_status.replaceAll('_', ' ').toUpperCase()}</small><h1>{printDocument.title}</h1><div className="ws-document-text">{printDocument.content}</div></>}</section>}
  </>;
}
