'use client';
import { useState } from 'react';
import { SiteNav, SiteFooter } from '@/components/site-chrome';
import { demoBrief } from '@/lib/workspace-demo';
export default function WorkspaceDemo() {
  const [result, setResult] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function prepare(task: string) { setBusy(true); setError(''); try { const response = await fetch('/api/workspace-demo', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ task }) }); const data = await response.json() as { content?: string; error?: string }; if (!response.ok) throw new Error(data.error); setResult(data.content || 'No draft returned.'); } catch(e) { setError(e instanceof Error ? e.message : 'The preview is unavailable.'); } finally { setBusy(false); } }
  return <main><SiteNav /><section className="workspace-main" style={{ padding: 'clamp(22px, 5vw, 70px)', maxWidth: 1300, margin: 'auto' }}><header className="admin-header"><div><small>FICTIONAL BUSINESS · LIVE AI PREVIEW</small><h1>From scattered notes to a useful next step.</h1><p>Try the document assistant with a sample brief. This preview never reads real client files or creates financial records.</p></div></header><div className="ws-grid"><section className="ws-card ws-form"><span className="ws-badge">SOURCE 1 · EXAMPLE ONLY</span><h2>Cedar Studio discovery note</h2><p>{demoBrief}</p><button disabled={busy} onClick={() => prepare('brief')}>Find the open questions</button><button className="ws-primary" disabled={busy} onClick={() => prepare('proposal')}>Prepare a proposed scope</button><p className="ws-note">A shared request limit keeps this preview available within a bounded AI budget. Nothing is issued or sent.</p></section><section className="ws-card"><h2>Review the assistant’s draft</h2>{busy && <p role="status">Reading the sample brief…</p>}{error && <p className="ws-alert" role="alert">{error}</p>}<div className="ws-document-text" aria-live="polite">{result || 'Choose a task to see how the assistant turns source material into a draft, with questions left open for a person.'}</div><p className="ws-note">In a business workspace, you choose your own documents, edit the result and save it with source references.</p></section></div><div className="ws-card" style={{ marginTop: 22 }}><h2>People control the commitments.</h2><p>Reviewed proposal → financial draft → issued invoice → recorded payment → receipt. The assistant helps prepare the work; it cannot approve scope, set prices or claim money has arrived.</p><a className="ws-demo-link" href="/agent-mapper">Explore a workflow for your business</a></div></section><SiteFooter /></main>;
}
