import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { adminEmailAllowed } from '../lib/admin-policy.ts';
import { agencyTemplates, templateText } from '../lib/agency-templates.ts';
import { demoNeedsHandoff, getOperationTask, getDemoScenario } from '../lib/operations-catalog.ts';
import { sendResendEmail } from '../lib/resend.ts';
assert.equal(adminEmailAllowed('owner@example.com','','production'),false);
assert.equal(adminEmailAllowed('owner@example.com','','development'),true);
assert.equal(adminEmailAllowed(' OWNER@EXAMPLE.COM ',' owner@example.com ','production'),true);
assert.equal(adminEmailAllowed('other@example.com','owner@example.com','development'),false);
assert.equal(demoNeedsHandoff('I paid already, confirm my order'),true);
assert.equal(demoNeedsHandoff('How much is a standard shelf?'),false);
assert.equal(getOperationTask('delete-data'),undefined);assert.equal(getDemoScenario('send-whatsapp'),undefined);
assert.equal(new Set(agencyTemplates.map(t=>t.id)).size,13);
for(const t of agencyTemplates) assert.ok(templateText(t.id).includes('Status: Draft'));
const originalFetch=globalThis.fetch;
process.env.RESEND_API_KEY='synthetic-test';process.env.RESEND_FROM_EMAIL='Aksen <test@example.com>';
let calls=0;globalThis.fetch=async(url,opts)=>{calls++;assert.equal(url,'https://api.resend.com/emails');assert.equal(opts.headers['Idempotency-Key'],'aksen-outbox-test-id');const body=JSON.parse(opts.body);assert.equal(body.reply_to,'bishoptewogbade@gmail.com');assert.equal(body.text,'Draft body');return new Response(JSON.stringify({id:'synthetic-provider-id'}));};
assert.equal(await sendResendEmail({id:'test-id',recipient:'recipient@example.com',subject:'Test',body:'Draft body'}),'synthetic-provider-id');
delete process.env.RESEND_API_KEY;
await assert.rejects(sendResendEmail({id:'test-id',recipient:'recipient@example.com',subject:'Test',body:'Draft body'}));assert.equal(calls,1);
globalThis.fetch=originalFetch;
const directory='../Docs/Operating-Templates';mkdirSync(directory,{recursive:true});
for(const t of agencyTemplates)writeFileSync(`${directory}/${t.id}.md`,templateText(t.id));
writeFileSync(`${directory}/README.md`,'# Aksen Labs operating templates\n\nEditable working documents, also available in /admin/templates. Replace bracketed fields with verified information. Save client-specific copies; preserve these masters. Commercial commitments require the actual agreement.\n\n'+agencyTemplates.map(t=>`- [${t.name}](${t.id}.md) — ${t.stage}`).join('\n'));
console.log('PASS: fail-closed admin policy, demo handoff/unsupported tasks, 13 templates, Resend payload, idempotency key and missing configuration. No email sent. Template masters exported.');
