/**
 * What the videos need generated, and why each one is generated rather than
 * photographed.
 *
 * The rule this file follows: generate the thing that cannot be photographed
 * honestly. A texture, a backdrop, an abstract field behind a headline, those
 * are fine. A picture of "a happy client" is not, because a viewer reads it as a
 * customer of ours and it is not one. Anything depicting a person or a business
 * carries `label`, which stamps the frame with what it is, the same way the site
 * labels its own demonstrations as fictional.
 *
 * `key` is the filename and the cache key. Change a prompt and you must change
 * the key, or the pipeline will keep serving the old file.
 */
export const assets = [
  {
    key: 'backdrop-hero-vertical',
    kind: 'image',
    aspectRatio: '9:16',
    prompt:
      'An abstract backdrop for a title card. Soft pale sage green paper texture, a faint network of thin connected lines and small nodes drifting across it, deep forest green accents. No text, no letters, no logos, no people, no user interface. Calm, matte, print-like, heavily negative space in the upper two thirds.',
  },
  {
    key: 'backdrop-close-dark',
    kind: 'image',
    aspectRatio: '9:16',
    prompt:
      'An abstract backdrop for a closing card. Very dark forest green, almost black, with a faint dot grid and one soft pool of lime green light in the lower right. No text, no letters, no logos, no people. Matte, calm, heavily negative space.',
  },
  {
    key: 'shopfront-texture',
    kind: 'image',
    aspectRatio: '9:16',
    // Depicts a place, so it is labelled. It stands in for the kind of business
    // this is for, and must never read as a photograph of a real customer.
    label: 'Illustration',
    prompt:
      'A warm illustrated interior of a small West African retail shop at dusk, shelves of stock, soft lamplight, seen from a distance, painterly and slightly abstract. No recognisable faces, no text, no signage, no logos.',
  },
];

/** Clips are expensive and slow, so none are generated by default. Move an entry
 *  into `assets` above when a composition actually calls for one. */
export const clips = [
  {
    key: 'opening-drift',
    kind: 'video',
    aspectRatio: '9:16',
    duration: 5,
    prompt:
      'A slow drifting abstract field of pale sage green with faint connected lines and small glowing nodes, gentle parallax, no camera shake. No text, no people, no interface.',
  },
];
