import { sql } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { getDb } from '@/db';
import { withRequestLog } from '@/lib/request-log';
import { runProspecting } from '@/lib/prospecting';
import { isDue, type Cadence } from '@/lib/automation-schedule';
import { auditEvents } from '@/db/schema';
import { runEditorialScout } from '@/lib/editorial-agent';
import { runFeedbackTriage, triageDue } from '@/lib/feedback-triage';

/**
 * The heartbeat. Something outside calls this on a timer and asks whether
 * anything is due; this decides, and runs it if so.
 *
 * Deliberately dumb on the outside and strict on the inside. The caller knows
 * nothing about cadence, so changing the schedule is an edit in the admin
 * rather than a change to whatever is doing the calling, and calling too often
 * is harmless because the gate refuses.
 *
 * Cloudflare's own cron triggers would be the natural home for this, but the
 * Worker entry is generated by vinext, which exports no scheduled handler and
 * emits an empty triggers block. Wrapping the generated entry to add one would
 * have to be redone on every build. An authenticated endpoint plus any timer
 * is less clever and does not break when the framework regenerates its output.
 */

/**
 * Timing-safe comparison. A plain === leaks the length of the matching prefix
 * through how long it takes to fail, and this secret is the only thing between
 * the open internet and something that spends model credits.
 */
function secretMatches(given: string, expected: string): boolean {
  if (given.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < given.length; i++)
    diff |= given.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}

async function POSTHandler(request: Request) {
  const expected = process.env.AUTOMATION_SECRET?.trim();
  // Absent secret refuses every call. The alternative, running when unset, is
  // an open trigger for anyone who guesses the path.
  if (!expected)
    return NextResponse.json(
      { error: 'Automation is not configured.' },
      { status: 503 },
    );

  const given = (
    request.headers.get('x-automation-secret') ||
    request.headers.get('authorization')?.replace(/^Bearer\s+/i, '') ||
    ''
  ).trim();
  if (!given || !secretMatches(given, expected))
    return NextResponse.json({ error: 'Not authorized.' }, { status: 401 });

  const db = getDb();
  const now = new Date();

  const campaigns = await db.execute(
    sql`SELECT id, owner_id, enabled, cadence, run_hour, max_per_day,
               last_scheduled_at, running_until
          FROM prospect_campaigns`,
  );

  // A timestamp column comes back as a string over the HTTP driver and as a
  // Date over a pooled connection. An unparseable value has to read as "never",
  // because a schedule comparing against Invalid Date would refuse silently.
  const asDate = (value: unknown): Date | null => {
    if (value instanceof Date)
      return Number.isNaN(value.getTime()) ? null : value;
    if (typeof value !== 'string' || !value) return null;
    const parsed = new Date(value);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  };

  const outcomes: {
    campaign: string;
    ran: boolean;
    reason?: string;
    added?: number;
  }[] = [];

  for (const row of campaigns.rows) {
    const campaignId = String(row.id);
    const ownerId = String(row.owner_id);

    // Counted from the runs themselves rather than from a tally column, so a
    // run that crashed before it could decrement anything cannot leave the
    // schedule permanently convinced it has already been used up.
    const [today] = (
      await db.execute(
        sql`SELECT count(*)::int AS n FROM prospect_runs
             WHERE campaign_id=${campaignId}
               AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC')`,
      )
    ).rows;

    const verdict = isDue(
      {
        cadence: String(row.cadence) as Cadence,
        runHour: Number(row.run_hour),
        maxPerDay: Number(row.max_per_day),
        enabled: Boolean(row.enabled),
      },
      now,
      {
        lastScheduledAt: asDate(row.last_scheduled_at),
        runsToday: Number(today?.n ?? 0),
        runningUntil: asDate(row.running_until),
      },
    );

    if (!verdict.due) {
      outcomes.push({
        campaign: campaignId,
        ran: false,
        reason: verdict.reason,
      });
      continue;
    }

    // Stamped before the run, not after. A run that fails still counts as an
    // attempt for today, or a failing campaign would retry on every heartbeat
    // and spend the daily allowance in an afternoon.
    await db.execute(
      sql`UPDATE prospect_campaigns SET last_scheduled_at=now() WHERE id=${campaignId}`,
    );

    try {
      // runProspecting claims the campaign with its own lock before doing any
      // work, and reports skipped if it cannot. The gate above is the schedule;
      // that lock is what stops two heartbeats overlapping.
      const result = await runProspecting(ownerId, campaignId, {
        scheduled: true,
      });
      outcomes.push({
        campaign: campaignId,
        ran: !result.skipped,
        added: result.added,
        reason: result.skipped ? result.note : undefined,
      });
    } catch (error) {
      outcomes.push({
        campaign: campaignId,
        ran: true,
        reason: error instanceof Error ? error.message : 'The run failed.',
      });
    }

    await db
      .insert(auditEvents)
      .values({
        id: crypto.randomUUID(),
        actorId: ownerId,
        actorType: 'system',
        action: 'automation.prospect_run',
        entityType: 'prospect_campaign',
        entityId: campaignId,
      })
      .catch(() => null);
  }

  const editorialOutcomes: {
    owner: string;
    ran: boolean;
    reason?: string;
    added?: number;
  }[] = [];
  const editorialSettings = await db.execute(sql`
    SELECT owner_id,enabled,cadence,run_hour,auto_draft,last_scheduled_at,running_until
      FROM editorial_settings`);
  for (const row of editorialSettings.rows) {
    const ownerId = String(row.owner_id);
    const [today] = (
      await db.execute(sql`
        SELECT count(*)::int AS n FROM editorial_runs
         WHERE owner_id=${ownerId} AND scheduled=true
           AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC')`)
    ).rows;
    const verdict = isDue(
      {
        cadence: String(row.cadence) as Cadence,
        runHour: Number(row.run_hour),
        maxPerDay: 1,
        enabled: Boolean(row.enabled),
      },
      now,
      {
        lastScheduledAt: asDate(row.last_scheduled_at),
        runsToday: Number(today?.n ?? 0),
        runningUntil: asDate(row.running_until),
      },
    );
    if (!verdict.due) {
      editorialOutcomes.push({
        owner: ownerId,
        ran: false,
        reason: verdict.reason,
      });
      continue;
    }
    await db.execute(
      sql`UPDATE editorial_settings SET last_scheduled_at=now() WHERE owner_id=${ownerId}`,
    );
    try {
      const result = await runEditorialScout(ownerId, {
        scheduled: true,
        autoDraft: Boolean(row.auto_draft),
      });
      editorialOutcomes.push({
        owner: ownerId,
        ran: !result.skipped,
        added: result.added,
        reason: result.skipped ? result.note : undefined,
      });
    } catch (error) {
      editorialOutcomes.push({
        owner: ownerId,
        ran: true,
        reason:
          error instanceof Error ? error.message : 'Editorial research failed.',
      });
    }
    await db
      .insert(auditEvents)
      .values({
        id: crypto.randomUUID(),
        actorId: ownerId,
        actorType: 'system',
        action: 'automation.editorial_run',
        entityType: 'editorial_settings',
        entityId: ownerId,
      })
      .catch(() => null);
  }

  // Feedback triage. Unlike the two above it has no cadence, because it is
  // event-shaped rather than clock-shaped: it runs when somebody has written in
  // and nobody has read it yet. Its own gate carries the off switch and the
  // daily ceiling.
  let triage: { ran: boolean; reason?: string; reviewed?: number } = {
    ran: false,
    reason: 'Not checked.',
  };
  try {
    const verdict = await triageDue();
    if (!verdict.due) {
      triage = { ran: false, reason: verdict.reason };
    } else {
      const result = await runFeedbackTriage({ scheduled: true });
      triage = {
        ran: !result.skipped,
        reviewed: result.reviewed,
        reason: result.note,
      };
      await db
        .insert(auditEvents)
        .values({
          id: crypto.randomUUID(),
          actorType: 'system',
          action: 'automation.feedback_triage',
          entityType: 'feedback_triage',
          entityId: 'default',
        })
        .catch(() => null);
    }
  } catch (error) {
    // A missing table on a deployment that has not run the migration must not
    // take the whole heartbeat down with it. Lead searching and editorial
    // research have nothing to do with the feedback board.
    triage = {
      ran: false,
      reason: error instanceof Error ? error.message : 'Triage failed.',
    };
  }

  // Always 200 when authorised, including when nothing was due. A timer that
  // sees a failure status for the ordinary case of "not yet" will eventually
  // be muted or removed by whoever is watching it.
  return NextResponse.json(
    {
      checked: campaigns.rows.length + editorialSettings.rows.length,
      outcomes,
      editorialOutcomes,
      triage,
      at: now.toISOString(),
    },
    { headers: { 'Cache-Control': 'no-store' } },
  );
}

export const POST = withRequestLog('/api/automation/tick', POSTHandler);
